services:
  glyphd:
    build: ./glyphd
    ports:
      - "8000:8000"
    volumes:  # Mount local code for live reload support
      - ./glyphd:/app
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  controlpanel:
    build:
      context: ./web
      dockerfile: ./apps/controlpanel/Dockerfile
    ports:
      - "3000:3000"
    volumes:  # Mount local code for live reload support
      - ./web:/app
    depends_on:
      - glyphd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
