import pandas as pd

# Create the pricing data from the previous research
pricing_data = [
    [
        "RTXPRO 6000 Blackwell Workstation Edition",
        "New",
        8299.99,
        "N/A",
        1,
        "Central Computer",
        "US Domestic",
        "Current",
        "https://www.centralcomputer.com/pny-nvidia-rtx-pro-6000-graphics-card-96gb-gddr6-24-064-cuda-cores-pci-express-5-0-x16-600w-vcnrtxpro6000b-pb.html",
        "Retail_Specialist",
        "~3% below MSRP; in-stock",
    ],
    [
        "RTX PRO 6000 Blackwell Workstation Edition",
        "New",
        8899.00,
        "Out of Stock",
        1,
        "Newegg (3C Expert)",
        "US Domestic",
        "Recent (2 days)",
        "https://www.newegg.com/p/2VV-000K-00143",
        "Retail_Major",
        "Slight premium vs. MSRP; OOS",
    ],
    [
        "RTX PRO 6000 Blackwell Workstation Edition",
        "New",
        9299.00,
        "Out of Stock",
        1,
        "Newegg (Newegg Direct)",
        "US Domestic",
        "Current",
        "https://www.newegg.com/p/N82E16888884001",
        "Retail_Major",
        "≈9% above MSRP; OOS",
    ],
    [
        "RTX PRO 6000 Blackwell Workstation Edition",
        "New",
        10999.00,
        "N/A",
        1,
        "B&H Photo",
        "US Domestic",
        "Current",
        "https://www.bhphotovideo.com/c/product/1895402-REG/nvidia_900-5g144-2200-000_rtx_pro_6000_blackwell.html",
        "Retail_Major",
        "Premium pricing; back-ordered",
    ],
    [
        "RTX PRO 6000 Blackwell Workstation Edition",
        "New",
        8565.00,
        "N/A",
        1,
        "PC Connection",
        "US Domestic",
        "Stale (>30 d)",
        "https://www.reddit.com/r/LocalLLaMA/comments/1jgnye9/rtx_pro_blackwell_pricing_listed/",
        "Retail_Specialist",
        "Original MSRP listing; now delisted",
    ],
    [
        "RTX PRO 6000 Blackwell Workstation Edition",
        "New",
        8031.08,
        "N/A",
        1,
        "SabrePC",
        "US Domestic",
        "Current",
        "https://www.sabrepc.com/900-5G144-2200-000-NVIDIA-S197828594",
        "Resale_Business",
        "≈6% below MSRP; non-returnable",
    ],
    [
        "RTX PRO 6000 Blackwell Workstation Edition",
        "New",
        7673.00,
        "N/A",
        1,
        "Directdial / Tech-America",
        "US/Canada",
        "Stale (>30 d)",
        "https://www.techradar.com/pro/nvidias-most-expensive-blackwell-card-gets-massive-price-cut-but-it-is-not-the-rtx-5090",
        "Retail_Specialist",
        "~10% below MSRP; preorder price cut",
    ],
    [
        "RTX PRO 6000 Blackwell Workstation Edition",
        "New",
        11400.00,
        "Pre-order",
        1,
        "Overclockers UK",
        "UK (EU)",
        "Stale (>30 d)",
        "https://www.overclockers.co.uk/nvidia-rtx-pro-6000-blackwell-workstation-edition-96gb-gddr7-graphics-card-gra-nvi-05609.html",
        "International",
        "High-price anomaly (+33% incl. VAT)",
    ],
    [
        "RTX PRO 6000 Blackwell Workstation Edition",
        "New",
        11990.00,
        "In Stock",
        "N/A",
        "ServerSupply",
        "US Domestic",
        "Current",
        "https://www.serversupply.com/GPU/GDDR7/96GB/NVIDIA/900-5G144-2200-001_414708.htm",
        "Resale_Business",
        "High-price anomaly (+40% over MSRP); may target enterprise rush demand",
    ],
    [
        "RTX PRO 6000 Blackwell Max-Q Workstation Edition",
        "New",
        10999.00,
        "N/A",
        1,
        "SHI International",
        "US Domestic",
        "Current",
        "https://texas.gs.shi.com/product/50042625/NVIDIA-RTX-PRO-6000-Blackwell-Max-Q",
        "Retail_Specialist",
        "300 W variant; preorder only",
    ],
]

# Define column headers
headers = [
    "Model",
    "Condition",
    "Price_USD",
    "Quantity",
    "Min_Order_Qty",
    "Seller",
    "Geographic_Region",
    "Listing_Age",
    "Source_URL",
    "Source_Type",
    "Bulk_Notes",
]

# Create DataFrame
df = pd.DataFrame(pricing_data, columns=headers)

# Save to CSV file named after the card
filename = "RTX_PRO_6000_Blackwell_pricing.csv"
df.to_csv(filename, index=False)

print(f"CSV file '{filename}' created successfully!")
print(f"File contains {len(df)} pricing entries")
print("\nFirst few rows:")
print(df.head())
